[package]
name = "magick_rust"
version = "0.14.0"
authors = ["Nathan Fiedler <nathanfiedler@fastmail.fm>"]
description = "Selection of Rust bindings for the ImageMagick library."
homepage = "https://github.com/nlfiedler/magick-rust"
repository = "https://github.com/nlfiedler/magick-rust.git"
readme = "README.md"
license = "Apache-2.0"
keywords = ["magickwand", "imagemagick"]
build = "build.rs"

[dependencies]
libc = "0.2.70"
imagemagick-sys = { version = "0.1", git = "https://github.com/michaelkirk/imagemagick-sys", branch = "mkirk/ubuntu" }
#imagemagick-sys = { version = "0.1", path = "../imagemagick-sys" }

[build-dependencies]
bindgen = "0.53.2"
pkg-config = "0.3.17"
